#!/usr/bin/env python3
"""Prepare an Android-only syscall compatibility overlay for pinned modernc libc.

No module cache, go.mod, server implementation, API or database schema is edited.
A generated build-driver module selects a copied/patched dependency outside the
immutable Go module cache. The Linux/amd64 copy retains normal Linux behavior;
only Android compilation selects the supported syscall entry points. ARM64 and
all original repository/module-cache source files are unchanged. See androidtv/acceptance/2026-09-30-native-compose.md.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

MODULE_VERSION = "v1.41.0"
MODULE_PATH = "modernc.org/libc"
SOURCE_FILENAME = "libc_linux_amd64.go"
HELPER_FILENAME = "seanime_android_compat_linux_amd64.go"
PINNED_SOURCE_SHA256 = "bf17852be812991fc8eb227f7e53a6ad24eba5e3baa61a466770efbf13f9c886"

# The versioned AOSP inputs are an audit reference, not a network build dependency.
POLICY_REFERENCES = [
    "https://android.googlesource.com/platform/bionic/+/refs/tags/android-16.0.0_r1/libc/SYSCALLS.TXT",
    "https://android.googlesource.com/platform/bionic/+/refs/tags/android-16.0.0_r1/libc/SECCOMP_ALLOWLIST_COMMON.TXT",
    "https://android.googlesource.com/platform/bionic/+/refs/tags/android-16.0.0_r1/libc/SECCOMP_ALLOWLIST_APP.TXT",
]

# All raw syscall IDs in the exact pinned source were audited. The *at replacements
# for OPEN/STAT/READLINK also avoid relying on temporary Android16 toolchain exceptions.
SYSCALL_MAPPING = {
    "SYS_LSTAT": "SYS_NEWFSTATAT(AT_FDCWD, path, stat, AT_SYMLINK_NOFOLLOW)",
    "SYS_STAT": "SYS_NEWFSTATAT(AT_FDCWD, path, stat, 0)",
    "SYS_OPEN": "SYS_OPENAT(AT_FDCWD, path, flags, mode)",
    "SYS_READLINK": "SYS_READLINKAT(AT_FDCWD, path, buffer, length)",
    "SYS_ACCESS": "SYS_FACCESSAT(AT_FDCWD, path, mode)",
    "SYS_UNLINK": "SYS_UNLINKAT(AT_FDCWD, path, 0)",
    "SYS_RMDIR": "SYS_UNLINKAT(AT_FDCWD, path, AT_REMOVEDIR)",
    "SYS_MKDIR": "SYS_MKDIRAT(AT_FDCWD, path, mode)",
    "SYS_RENAME": "SYS_RENAMEAT(AT_FDCWD, old, AT_FDCWD, new)",
    "SYS_SYMLINK": "SYS_SYMLINKAT(target, AT_FDCWD, link)",
    "SYS_CHMOD": "SYS_FCHMODAT(AT_FDCWD, path, mode)",
    "SYS_CHOWN": "SYS_FCHOWNAT(AT_FDCWD, path, owner, group, 0)",
    "SYS_LINK": "SYS_LINKAT(AT_FDCWD, old, AT_FDCWD, new, 0)",
    "SYS_MKNOD": "SYS_MKNODAT(AT_FDCWD, path, mode, device)",
    "SYS_PIPE": "SYS_PIPE2(pipefd, 0)",
    "SYS_DUP2": "SYS_DUP3(old, new, 0); identical fd is validated with F_GETFD",
    "SYS_UTIME": "SYS_UTIMENSAT with seconds-to-timespec conversion; null means current time",
    "SYS_UTIMES": "SYS_UTIMENSAT with validated microseconds-to-timespec conversion",
    "SYS_TIME": "SYS_CLOCK_GETTIME(CLOCK_REALTIME); Xtime retains its original optional tloc write",
    "SYS_ALARM": "SYS_SETITIMER(ITIMER_REAL); preserve Linux alarm rounding",
}
PASSTHROUGH_SYSCALLS = {
    "SYS_RT_SIGACTION", "SYS_FCNTL", "SYS_FSTAT", "SYS_MMAP", "SYS_MREMAP",
    "SYS_FTRUNCATE", "SYS_LSEEK", "SYS_GETRLIMIT", "SYS_SETRLIMIT",
}

ANDROID_SYSCALL_HELPER = r'''// Code generated by scripts/prepare-android-go-compat.py; DO NOT EDIT.
// Android x86_64 compatibility for modernc.org/libc v1.41.0 (BSD-3-Clause).
// This file's Linux/amd64 suffix matches the pinned source being overlaid.
// Host Go/gomobile tools retain the original behavior through the GOOS guard.
package libc

import (
    "runtime"
    "unsafe"

    "golang.org/x/sys/unix"
)

// seanimeAndroidSyscall preserves the caller's pointer/flag/errno contract while
// choosing Android's supported kernel entry point. No seccomp policy is changed.
// AT_FDCWD must be sign-extended on amd64, never converted through uint32.
//
//go:uintptrescapes
func seanimeAndroidSyscall(trap, a1, a2, a3 uintptr) (uintptr, uintptr, unix.Errno) {
    if runtime.GOOS != "android" {
        return unix.Syscall(trap, a1, a2, a3)
    }
    const atFDCWD = ^uintptr(99) // int64(-100), represented as a syscall word.
    switch trap {
    case unix.SYS_LSTAT:
        return unix.Syscall6(unix.SYS_NEWFSTATAT, atFDCWD, a1, a2, unix.AT_SYMLINK_NOFOLLOW, 0, 0)
    case unix.SYS_STAT:
        return unix.Syscall6(unix.SYS_NEWFSTATAT, atFDCWD, a1, a2, 0, 0, 0)
    case unix.SYS_OPEN:
        return unix.Syscall6(unix.SYS_OPENAT, atFDCWD, a1, a2, a3, 0, 0)
    case unix.SYS_READLINK:
        return unix.Syscall6(unix.SYS_READLINKAT, atFDCWD, a1, a2, a3, 0, 0)
    case unix.SYS_ACCESS:
        return unix.Syscall6(unix.SYS_FACCESSAT, atFDCWD, a1, a2, 0, 0, 0)
    case unix.SYS_UNLINK:
        return unix.Syscall6(unix.SYS_UNLINKAT, atFDCWD, a1, 0, 0, 0, 0)
    case unix.SYS_RMDIR:
        return unix.Syscall6(unix.SYS_UNLINKAT, atFDCWD, a1, unix.AT_REMOVEDIR, 0, 0, 0)
    case unix.SYS_MKDIR:
        return unix.Syscall6(unix.SYS_MKDIRAT, atFDCWD, a1, a2, 0, 0, 0)
    case unix.SYS_RENAME:
        return unix.Syscall6(unix.SYS_RENAMEAT, atFDCWD, a1, atFDCWD, a2, 0, 0)
    case unix.SYS_SYMLINK:
        return unix.Syscall6(unix.SYS_SYMLINKAT, a1, atFDCWD, a2, 0, 0, 0)
    case unix.SYS_CHMOD:
        return unix.Syscall6(unix.SYS_FCHMODAT, atFDCWD, a1, a2, 0, 0, 0)
    case unix.SYS_CHOWN:
        return unix.Syscall6(unix.SYS_FCHOWNAT, atFDCWD, a1, a2, a3, 0, 0)
    case unix.SYS_LINK:
        return unix.Syscall6(unix.SYS_LINKAT, atFDCWD, a1, atFDCWD, a2, 0, 0)
    case unix.SYS_MKNOD:
        return unix.Syscall6(unix.SYS_MKNODAT, atFDCWD, a1, a2, a3, 0, 0)
    case unix.SYS_PIPE:
        return unix.Syscall(unix.SYS_PIPE2, a1, 0, 0)
    case unix.SYS_DUP2:
        if a1 == a2 {
            // dup3(a,a,0) is EINVAL; dup2(a,a) succeeds only for an open fd.
            _, _, err := unix.Syscall(unix.SYS_FCNTL, a1, unix.F_GETFD, 0)
            if err != 0 { return ^uintptr(0), 0, err }
            return a1, 0, 0
        }
        return unix.Syscall(unix.SYS_DUP3, a1, a2, 0)
    case unix.SYS_UTIME, unix.SYS_UTIMES:
        // utimensat treats a null path as an fd operation; legacy utime(s) does not.
        if a1 == 0 { return ^uintptr(0), 0, unix.EFAULT }
        if a2 == 0 {
            return unix.Syscall6(unix.SYS_UTIMENSAT, atFDCWD, a1, 0, 0, 0, 0)
        }
        var times [2]unix.Timespec
        if trap == unix.SYS_UTIME {
            seconds := (*[2]int64)(unsafe.Pointer(a2))
            times[0].Sec, times[1].Sec = seconds[0], seconds[1]
        } else {
            values := (*[2]unix.Timeval)(unsafe.Pointer(a2))
            for i := range times {
                // Validate before multiplication, including the overflow cases.
                if values[i].Usec < 0 || values[i].Usec >= 1_000_000 {
                    return ^uintptr(0), 0, unix.EINVAL
                }
                times[i].Sec, times[i].Nsec = values[i].Sec, values[i].Usec * 1_000
            }
        }
        r1, r2, err := unix.Syscall6(unix.SYS_UTIMENSAT, atFDCWD, a1, uintptr(unsafe.Pointer(&times[0])), 0, 0, 0)
        runtime.KeepAlive(&times)
        return r1, r2, err
    case unix.SYS_TIME:
        var now unix.Timespec
        _, _, err := unix.Syscall(unix.SYS_CLOCK_GETTIME, unix.CLOCK_REALTIME, uintptr(unsafe.Pointer(&now)), 0)
        runtime.KeepAlive(&now)
        if err != 0 { return ^uintptr(0), 0, err }
        // The pinned Xtime caller already writes *tloc after success.
        return uintptr(now.Sec), 0, 0
    case unix.SYS_ALARM:
        var next, old struct { Interval, Value unix.Timeval }
        next.Value.Sec = int64(uint32(a1))
        _, _, err := unix.Syscall(unix.SYS_SETITIMER, unix.ITIMER_REAL,
            uintptr(unsafe.Pointer(&next)), uintptr(unsafe.Pointer(&old)))
        runtime.KeepAlive(&next)
        runtime.KeepAlive(&old)
        if err != 0 { return ^uintptr(0), 0, err }
        return seanimeAndroidAlarmSeconds(old.Value.Sec, old.Value.Usec), 0, 0
    default:
        return unix.Syscall(trap, a1, a2, a3)
    }
}

// Match kernel/time/itimer.c's alarm_setitimer, including sub-second timers.
func seanimeAndroidAlarmSeconds(seconds, microseconds int64) uintptr {
    if (seconds == 0 && microseconds != 0) || microseconds >= 500_000 { seconds++ }
    return uintptr(seconds)
}
'''


def patch_source(source: bytes) -> bytes:
    digest = hashlib.sha256(source).hexdigest()
    if digest != PINNED_SOURCE_SHA256:
        raise ValueError(f"Refusing unreviewed {MODULE_PATH} {MODULE_VERSION} source: SHA-256 {digest}, expected {PINNED_SOURCE_SHA256}")
    constants = set(re.findall(rb"unix\.(SYS_[A-Z0-9_]+)", source))
    expected = {value.encode() for value in SYSCALL_MAPPING.keys() | PASSTHROUGH_SYSCALLS}
    if constants != expected:
        raise ValueError(f"Pinned syscall inventory mismatch: {sorted(constants ^ expected)}")
    if source.count(b"unix.Syscall(") != 26:
        raise ValueError("Pinned raw syscall call count changed")
    return source.replace(b"unix.Syscall(", b"seanimeAndroidSyscall(")


def _atomic_write(path: Path, contents: bytes) -> None:
    if path.exists() and path.read_bytes() == contents:
        return
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(contents)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def prepare_overlay(module_dir: Path, output_dir: Path) -> Path:
    module_dir, output_dir = Path(module_dir).resolve(), Path(output_dir).resolve()
    if output_dir == module_dir or module_dir in output_dir.parents:
        raise ValueError("Overlay output must not be inside the immutable dependency directory")
    if module_dir.parent.name == "modernc.org" and (output_dir == module_dir.parent.parent or module_dir.parent.parent in output_dir.parents):
        raise ValueError("Overlay output must not be inside the Go module cache")
    original = module_dir / SOURCE_FILENAME
    source = original.read_bytes()
    patched = patch_source(source)  # Fail before creating any output on drift.
    virtual_helper = module_dir / HELPER_FILENAME
    if virtual_helper.exists():
        raise ValueError(f"Unexpected dependency source would be shadowed: {virtual_helper}")
    output_dir.mkdir(parents=True, exist_ok=True)
    # Go 1.27 forbids overlays beneath GOMODCACHE. Stage real source files first,
    # then use a generated driver module's local replacement to select the stage.
    stage = output_dir / "staged-libc"
    stage.mkdir(exist_ok=True)
    allowed = {path.relative_to(module_dir) for path in module_dir.rglob("*") if path.is_file()} | {Path(HELPER_FILENAME)}
    for source_file in sorted(module_dir.rglob("*")):
        if source_file.is_symlink():
            raise ValueError(f"Unexpected module-cache symlink: {source_file}")
        relative = source_file.relative_to(module_dir)
        destination = stage / relative
        if source_file.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
        elif source_file.is_file():
            destination.parent.mkdir(parents=True, exist_ok=True)
            _atomic_write(destination, patched if relative == Path(SOURCE_FILENAME) else source_file.read_bytes())
    unexpected = {path.relative_to(stage) for path in stage.rglob("*") if path.is_file()} - allowed
    if unexpected:
        raise ValueError(f"Unexpected generated staging files: {sorted(str(path) for path in unexpected)}")
    staged_original = stage / SOURCE_FILENAME
    staged_helper = stage / HELPER_FILENAME
    copied = output_dir / SOURCE_FILENAME
    helper = output_dir / HELPER_FILENAME
    overlay = output_dir / "overlay.json"
    helper_bytes = ANDROID_SYSCALL_HELPER.encode()
    _atomic_write(copied, patched)
    _atomic_write(helper, helper_bytes)
    _atomic_write(staged_helper, helper_bytes)
    _atomic_write(overlay, (json.dumps({"Replace": {str(staged_original): str(copied), str(staged_helper): str(helper)}}, indent=2, sort_keys=True) + "\n").encode())
    _atomic_write(output_dir / "compatibility.json", (json.dumps({
        "module": MODULE_PATH, "version": MODULE_VERSION,
        "staged_module": str(stage), "overlay": str(overlay),
        "source_sha256": PINNED_SOURCE_SHA256,
        "patched_source_sha256": hashlib.sha256(patched).hexdigest(),
        "helper_sha256": hashlib.sha256(helper_bytes).hexdigest(),
        "scope": "GOOS=android and GOARCH=amd64 only; non-Android runtime.GOOS branch forwards original syscalls",
        "bind_contract": {"cwd": str(output_dir / "driver"), "GOWORK": "off", "package": "seanime/mobile", "overlay_flag_required": False},
        "alarm_precision": "SETITIMER reports microseconds; unlike raw Linux ALARM, a remaining 1-999ns interval may round to zero. SQLite does not use Xalarm.",
        "mapping": SYSCALL_MAPPING, "unchanged_syscalls": sorted(PASSTHROUGH_SYSCALLS),
        "policy_references": POLICY_REFERENCES,
        "pointer_precondition": "utime/utimes require valid non-null C input pointers; time requires valid writable non-null tloc storage in its existing Xtime caller; no arbitrary invalid-address EFAULT equivalence is claimed",
    }, indent=2, sort_keys=True) + "\n").encode())
    # Verify the source was not mutated while outputs were prepared.
    if original.read_bytes() != source:
        raise RuntimeError("Dependency source changed during overlay generation")
    return overlay


def prepare_driver(repo_root: Path, output_dir: Path) -> Path:
    repo_root, output_dir = Path(repo_root).resolve(), Path(output_dir).resolve()
    original_mod = (repo_root / "go.mod").read_bytes()
    original_sum = (repo_root / "go.sum").read_bytes()
    text = original_mod.decode()
    if not re.search(r"(?m)^module seanime\s*$", text):
        raise ValueError("Expected the unchanged seanime root module")
    # Local relative replacement paths depend on cwd; refuse silent reinterpretation.
    env = dict(os.environ, GOWORK="off")
    metadata = json.loads(subprocess.check_output(["go", "mod", "edit", "-json"], cwd=repo_root, env=env, text=True))
    for replacement in metadata.get("Replace") or []:
        target = replacement["New"]
        if not target.get("Version") and not Path(target["Path"]).is_absolute():
            raise ValueError("A relative root module replacement requires an explicit driver review")
    driver = output_dir / "driver"
    driver.mkdir(parents=True, exist_ok=True)
    text = re.sub(r"(?m)^module seanime\s*$", "module seanime.android.build", text, count=1)
    text += "\n// Generated Android build driver; root manifests remain unchanged.\n"
    text += "require seanime v0.0.0\n"
    text += "replace seanime => " + json.dumps(str(repo_root)) + "\n"
    text += "replace modernc.org/libc => " + json.dumps(str(output_dir / "staged-libc")) + "\n"
    _atomic_write(driver / "go.mod", text.encode())
    _atomic_write(driver / "go.sum", original_sum)
    if (repo_root / "go.mod").read_bytes() != original_mod or (repo_root / "go.sum").read_bytes() != original_sum:
        raise RuntimeError("Root manifests changed during driver preparation")
    return driver


def resolve_module(repo_root: Path) -> Path:
    env = dict(os.environ, GOWORK="off")
    metadata = json.loads(subprocess.check_output(["go", "list", "-mod=readonly", "-m", "-json", MODULE_PATH], cwd=repo_root, env=env, text=True))
    if metadata.get("Path") != MODULE_PATH or metadata.get("Version") != MODULE_VERSION or metadata.get("Replace"):
        raise ValueError(f"Expected unchanged {MODULE_PATH} {MODULE_VERSION}, got {metadata.get('Version')} or a replacement")
    if not metadata.get("Dir"):
        # Download outside the repository module so Go cannot update its sum file.
        with tempfile.TemporaryDirectory(prefix="seanime-libc-download-") as scratch:
            downloaded = json.loads(subprocess.check_output(["go", "mod", "download", "-json", f"{MODULE_PATH}@{MODULE_VERSION}"], cwd=scratch, env=env, text=True))
        if downloaded.get("Error") or downloaded.get("Path") != MODULE_PATH or downloaded.get("Version") != MODULE_VERSION or not downloaded.get("Dir"):
            raise ValueError("Failed to materialize the exact pinned libc module")
        metadata = downloaded
    return Path(metadata["Dir"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--module-dir", type=Path, help="Use an already downloaded, checksum-pinned module directory")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    module_dir = args.module_dir or resolve_module(args.repo_root)
    overlay = prepare_overlay(module_dir, args.output_dir)
    prepare_driver(args.repo_root, args.output_dir)
    print(args.output_dir.resolve() / "driver")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
